In [3]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv(r'C:\Users\nishi\OneDrive\Desktop\Creditcardf.csv')

In [5]:
df.head(10)

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   
5   2.0 -0.425966  0.960523  1.141109 -0.168252  0.420987 -0.029728  0.476201   
6   4.0  1.229658  0.141004  0.045371  1.202613  0.191881  0.272708 -0.005159   
7   7.0 -0.644269  1.417964  1.074380 -0.492199  0.948934  0.428118  1.120631   
8   7.0 -0.894286  0.286157 -0.113192 -0.271526  2.669599  3.721818  0.370145   
9   9.0 -0.338262  1.119593  1.044367 -0.222187  0.499361 -0.246761  0.651583   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   
5  0.260314 -0.568671  ... -0.208254 -0.559825 -0.026398 -0.371427 -0.232794   
6  0.081213  0.464960  ... -0.167716 -0.270710 -0.154104 -0.780055  0.750137   
7 -3.807864  0.615375  ...  1.943465 -1.015455  0.057504 -0.649709 -0.415267   
8  0.851084 -0.392048  ... -0.073425 -0.268092 -0.204233  1.011592  0.373205   
9  0.069539 -0.736727  ... -0.246914 -0.633753 -0.120794 -0.385050 -0.069733   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  
5  0.105915  0.253844  0.081080    3.67      0  
6 -0.257237  0.034507  0.005168    4.99      0  
7 -0.051634 -1.206921 -1.085339   40.80      0  
8 -0.384157  0.011747  0.142404   93.20      0  
9  0.094199  0.246219  0.083076    3.68      0  

[10 rows x 31 columns]

In [5]:
class_names = {0:'Not Fraud', 1:'Fraud' }
print(df.Class.value_counts().rename(index=class_names))

Not Fraud    284315
Fraud           492
Name: Class, dtype: int64


In [7]:
# SELECTING FEATURE AND TARGET
feature_names = df.iloc[:, 1:30].columns
feature_names

Index(['V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11',
       'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21',
       'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount'],
      dtype='object')

In [9]:
target = df.iloc[:1, 30:].columns
target

Index(['Class'], dtype='object')

In [12]:
data_features = df[feature_names]
data_features.head()

V1        V2        V3        V4        V5        V6        V7  \
0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9       V10  ...       V20       V21       V22       V23  \
0  0.098698  0.363787  0.090794  ...  0.251412 -0.018307  0.277838 -0.110474   
1  0.085102 -0.255425 -0.166974  ... -0.069083 -0.225775 -0.638672  0.101288   
2  0.247676 -1.514654  0.207643  ...  0.524980  0.247998  0.771679  0.909412   
3  0.377436 -1.387024 -0.054952  ... -0.208038 -0.108300  0.005274 -0.190321   
4 -0.270533  0.817739  0.753074  ...  0.408542 -0.009431  0.798278 -0.137458   

        V24       V25       V26       V27       V28  Amount  
0  0.066928  0.128539 -0.189115  0.133558 -0.021053  149.62  
1 -0.339846  0.167170  0.125895 -0.008983  0.014724    2.69  
2 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  378.66  
3 -1.175575  0.647376 -0.221929  0.062723  0.061458  123.50  
4  0.141267 -0.206010  0.502292  0.219422  0.215153   69.99  

[5 rows x 29 columns]

In [13]:
data_target = df[target]
data_target.head()

Class
0      0
1      0
2      0
3      0
4      0

In [14]:
# Splitting the data into trainin and testing set
from sklearn.model_selection import train_test_split
np.random.seed(123)
x_train, x_test, y_train, y_test = train_test_split(data_features, data_target, test_size=0.3, random_state=1)

In [15]:
# Now creating a logistics Regression model for 
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()

In [16]:
# Instead of creating a function we could have done it separetely but it would make our work a bit simpler
# Now lets create a function that will calculate all of the following task 1.) model.fit 2.) model.predict 3.) confusion_matrix
from sklearn.metrics import confusion_matrix, cohen_kappa_score
from sklearn.metrics import f1_score, recall_score
def run_model(model, x_train, x_test, y_train, y_test):
    model.fit(x_train, y_train.values.ravel())
    pred = model.predict(x_test)
    matrix = confusion_matrix(y_test, pred)
    return matrix, pred

In [21]:
# We also need some helper function. Now printstat will display and compile the rsult from our model
def printstats(cmat, y_test, pred):
    # Seperating out the confusion matrix component( we are separating the components so that we could use it in calculating the accuracy of the model easily)
    tpos = cmat[0][0]
    fneg = cmat[1][1]
    fpos = cmat[0][1]
    tneg = cmat[1][0]
    # finally printing out everything
    print(cmat)
    print('Accuracy:' + str(np.round(100*float(tpos+fneg)/float(tpos+fneg+fpos+tneg), 2)) + '%')
    print('Cohen Kappa:' + str(np.round(cohen_kappa_score(y_test, pred), 3)))
    print('Sensitivity/Recall for the model:' + str(np.round(recall_score(y_test, pred), 2)))
    print('F-1 Score for the model:' + str(np.round(f1_score(y_test, pred), 2)))

In [22]:
cmat, pred = run_model(lr, x_train, x_test, y_train, y_test)
printstats(cmat, y_test, pred)

C:\Users\nishi\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[85290    18]
 [   54    81]]
Accuracy:99.92%
Cohen Kappa:0.692
Sensitivity/Recall for the model:0.6
F-1 Score for the model:0.69


In [31]:
# now one might think that 99.92% is a really great accuracy. But if we see the total no. Actual fraud cases that were predicted as non fraud cases is really high
print('Percentage of undetected Fraud Cases : ' + str(100*(54/135)) + '%') # So our model has wrongly classified 40% of fraud cases as non fraud

Percentage of undetected Fraud Cases : 40.0%


In [28]:
# Now why did this happended. Reason is : we have overwhelmingly high no. of non fraud cases(284315) in comparision to very few non fraud cases(495)
# so basically our dataset is highly imbalance and skewed
# So basically here we can conclude that accuracy is not a right metrics to decide whether a model is good or not.
# for this particular case of unbalanced problem we want cohen_kappa, recall and f1_score as close as possible to 1

In [29]:
# Now lets try Random forest classifer and see how does that work
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=100, n_jobs=4)
cmat, pred = run_model(rf, x_train, x_test, y_train, y_test)
printstats(cmat, y_test, pred)

[[85297    11]
 [   31   104]]
Accuracy:99.95%
Cohen Kappa:0.832
Sensitivity/Recall for the model:0.77
F-1 Score for the model:0.83


In [59]:
# Resampling the dataset using undersampling technique. What we are trying to do is get a even split between fraud and non fraud records using Undersapling

# First lets pull out a indices from fraud row
fraud_indices = df[df.Class==1].index
fraud_indices # This will give us the row no. of all the fraud cases


Int64Index([   541,    623,   4920,   6108,   6329,   6331,   6334,   6336,
              6338,   6427,
            ...
            274382, 274475, 275992, 276071, 276864, 279863, 280143, 280149,
            281144, 281674],
           dtype='int64', length=492)

In [54]:
## Now lets get the indices for valid rows
valid_indices = df[df.Class==0].index
valid_indices

Int64Index([     0,      1,      2,      3,      4,      5,      6,      7,
                 8,      9,
            ...
            284797, 284798, 284799, 284800, 284801, 284802, 284803, 284804,
            284805, 284806],
           dtype='int64', length=284315)

In [68]:
# We will be using equal no. fraud and valid records for training the model. That's is the reason why we are calculating the length of the Fraud records so that we can use it later
fraud_records = len(df[df.Class==1])
fraud_records

492

In [72]:
# Now lets collect equal samples of each type
under_sampled_indices = np.random.choice(valid_indices,fraud_records, False)
under_sampled_indices

array([ 58384, 131092, 163005, 106002,  86755,   6856, 127416,  85457,
        37165, 107935,   4153, 230208, 209225,  45048, 215630, 142398,
       218157, 127397, 116310, 158018,  84354, 115453,  36849, 122575,
       121682,  74206, 248219, 155554, 102961, 159598, 278121, 106505,
        54519, 205126,  44334, 193919, 258139, 256551,  39284, 116553,
       247160, 218149, 141296,  50264, 202968,   3052,  81141, 272722,
       200714, 163131,  35184, 159570,  91743,  97765,  70148, 124091,
         9564,  49690, 163014, 214295,  97058,  75745, 238760, 168646,
        71905,  22943,  37057, 240808, 198394, 213856, 177912,  39428,
       113540, 202103, 277500,  61797, 282920, 216012,   3229, 122827,
       134646,  55734, 201187, 241495,  77654, 111500, 219477, 284758,
       146088, 171624, 269742, 244519, 159506,  38438, 145886,  48907,
       110589,  44005, 189129,  40578,  22117, 186679, 170885, 108210,
       133097,  78661, 141567,  41542, 112170,  67494,  34244,  75923,
      

In [73]:
# creating a new df containing 492 records for valid and fraud cases. We will use this data to train our model and once training is done we will be implementing it in the entire test set
df_undersampled = df.iloc[np.concatenate([fraud_indices, under_sampled_indices]), :]

In [74]:
feature_data_undersampled = df_undersampled.iloc[:, 1:30]
target_data_undersampled = df_undersampled.Class

In [78]:
x_train_US, x_test_US, y_train_US, y_test_US = train_test_split(feature_data_undersampled,target_data_undersampled,test_size = 0.3)

In [79]:
lr_undersampled = LogisticRegression()

In [80]:
# Here we are working on a small subset of data to train our model
cmat, pred = run_model(lr_undersampled, x_train_US, x_test_US, y_train_US, y_test_US)
printstats(cmat, y_test_US, pred)

[[152   4]
 [ 12 128]]
Accuracy:94.59%
Cohen Kappa:0.891
Sensitivity/Recall for the model:0.91
F-1 Score for the model:0.94


C:\Users\nishi\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [83]:
# Now we will be using this trained model with our entire test dataset
cmat, pred = run_model(lr_undersampled, x_train_US, x_test,  y_train_US, y_test)
printstats(cmat, y_test, pred)

C:\Users\nishi\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  Returns


[[82288  3020]
 [   12   123]]
Accuracy:96.45%
Cohen Kappa:0.072
Sensitivity/Recall for the model:0.91
F-1 Score for the model:0.08
